# Generated by Django 6.0.4 on 2026-05-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerlike',
            options={'verbose_name': 'Лайк ответа', 'verbose_name_plural': 'Лайки ответов'},
        ),
        migrations.AlterModelOptions(
            name='questionlike',
            options={'verbose_name': 'Лайк вопроса', 'verbose_name_plural': 'Лайки вопросов'},
        ),
        migrations.RemoveField(
            model_name='answerlike',
            name='is_positive',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='is_positive',
        ),
        migrations.AddField(
            model_name='answerlike',
            name='is_like',
            field=models.BooleanField(choices=[(True, 'Лайк'), (False, 'Дизлайк')], default=True, verbose_name='Тип оценки'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='is_like',
            field=models.BooleanField(choices=[(True, 'Лайк'), (False, 'Дизлайк')], default=True, verbose_name='Тип оценки'),
        ),
    ]
