# Generated by Django 6.0.4 on 2026-05-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_answer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
