# Generated by Django 6.0.4 on 2026-05-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_answerlike_user_alter_questionlike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
    ]
