# Generated by Django 6.0.4 on 2026-05-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_tag_question_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(max_length=30000, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество ответов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=50000, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='question_count',
            field=models.IntegerField(default=0, verbose_name='Количество вопросов с тегом'),
        ),
    ]
