# Generated by Django 6.0.4 on 2026-05-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_answer_content_alter_answer_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Название'),
        ),
    ]
