# Generated by Django 6.0.4 on 2026-05-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default-avatar.png', upload_to='users/avatars/%Y/%m/%d/'),
        ),
    ]
