# Generated by Django 6.0.4 on 2026-05-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default-avatar.jpg', upload_to='users/avatars/%Y/%m/%d/'),
        ),
    ]
