# Generated by Django 6.0.4 on 2026-05-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_avatar_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ответов дано'),
        ),
        migrations.AddField(
            model_name='profile',
            name='questions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Вопросов задано'),
        ),
    ]
